# --- Defaults ---

num_envs: 1

test_nepisode: 20
test_interval: 2000

log_interval: 2000

runner_log_interval: 2000
learner_log_interval: 2000

t_max: 10000

save_model: False
save_model_interval: 50000

checkpoint_path: ""
evaluate: False
load_step: 0

l2_reg_coef: 0

gamma: 0.99

repetitions: 5

action_selector: ~

n_batches_to_sample: 1

optimizer_epsilon: 0.00000001

use_cuda: True

env_args:
    obs_entity_mode: False
    state_entity_mode: False

save_model_end: True

buffer_transitions: False

start_steps: 0

save_frames: False

increase_step_counter: False
use_training_steps_to_compute_target_noise: False

critic_use_previous_transitions: False
num_previous_transitions: 0

use_min_to_update_actor: True

decay_type: linear