# --- COMIX specific parameters ---

name: "comix"

add_agent_id: True
add_last_action: True

num_envs: 8
batch_size: 50
buffer_size: 4000
t_max: 4000000

discretize_actions: False
double_q: False

start_steps: 0
sigma_start: 0.2
sigma_finish: 0.05
sigma_anneal_time: 3000000

gamma: 0.99

lr: 0.001
grad_norm_clip: 50

learner: "continuous_q_learner"
controller: "comix_controller"
agent: "rnn"
mixer: "qmix"

mixing_embed_dim: 128
hypernet_layers: 2
hypernet_embed: 64
hyper_initialization_nonzeros: 0
hidden_dim: 64

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 200

save_model: False
save_model_interval: 20000

lr_decay: False
lr_decay_gamma: 0.9
lr_decay_episodes: 20
