# --- DDPG specific parameters ---

name: "ddpg"

seed: 1412

runner: "parallel"
batch_size_run: 8
batch_size: 50
buffer_size: 4000
t_max: 1000000

double_q: False

gamma: 0.99

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.9
lr_decay_episodes: 20

grad_norm_clip_actor: 50
grad_norm_clip_critic: 50

#optimizer_epsilon: 0.01

learner: "ddpg_learner"
mac: "ddpg_mac"
critic_controller: "ddpg_controller"
agent: "rnn_mean_log_std"
critic: "rnn"
mixer: "qmix"

hidden_dim: 64

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 200

save_model: False
save_model_interval: 50000

n_batches_to_sample: 1

#load_step: 561000
#checkpoint_path: "D:/MAI/TFM/TFM/results/pistonball_reward_2_actions/facmac_pettingzoo/196/models" 
#evaluate: True # Evaluate model for test_nepisode episodes and quit (no training)