# --- DDPG specific parameters ---

name: "ddpg"

seed: 1412

runner: "parallel"
buffer_transitions: True
batch_size_run: 1
n_batches_to_sample: 512
batch_size: 256
buffer_size: 1000000
t_max: 1000000

start_steps: 10000
sigma_start: 0.5
sigma_finish: 0.05
sigma_anneal_time: 1000000

gamma: 0.99

lr: 0.0001
critic_lr: 0.0001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.9
lr_decay_episodes: 20

grad_norm_clip_actor: 0.5
grad_norm_clip_critic: 0.5

#optimizer_epsilon: 0.01

learner: "ddpg_learner"
mac: "ddpg_mac"
critic_controller: "ddpg_controller"
agent: "mlp_actor"
critic: "mlp"
mixer: "qmix"

hidden_dim: 256

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 200

save_model: False
save_model_interval: 50000

save_model_end: True

#load_step: 561000
#checkpoint_path: "D:/MAI/TFM/TFM/results/pistonball_reward_2_actions/facmac_pettingzoo/196/models" 
#evaluate: True # Evaluate model for test_nepisode episodes and quit (no training)