# --- DQN specific parameters ---

name: 'dqn'

seed: 1412

add_agent_id: True
add_last_action: True
obs_individual_obs: False

action_selector: "epsilon_greedy_single"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000
evaluation_epsilon: 0

runner: "episode"
batch_size_run: 1
batch_size: 20
buffer_size: 1000
t_max: 300000

lr: 0.01
lr_decay: True
lr_decay_gamma: 0.5
lr_decay_episodes: 500

grad_norm_clip: 0.5
optimizer_epsilon: 0.00000001

learner: "dqn_learner"
mac: "dqn_mac"
agent: "rnn"

hidden_dim: 256

target_update_mode: 'soft'
hard_update_interval: 200
target_update_tau: 0.005

save_model: False
save_model_interval: 5000

double_q: True

standardise_returns: False
standardise_rewards: False
