# --- FACMAC TD3 specific parameters ---

name: "facmac_td3"

seed: 0

obs_agent_id: True
obs_last_action: True
critic_obs_agent_id: True
critic_obs_last_action: False

runner: "episode"
buffer_transitions: False
batch_size_run: 1
n_batches_to_sample: 1
batch_size: 100
buffer_size: 1000
t_max: 1500000

start_steps: 0

sigma_start: 0.2
sigma_finish: 0.05
sigma_anneal_time: 1500000

target_sigma_start: 0.1
target_sigma_finish: 0.05
target_sigma_anneal_time: 1500000

gamma: 0.99

update_actor_targets_freq: 1
target_noise_clipping: 0.2

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.9
lr_decay_episodes: 20

grad_norm_clip_actor: 50
grad_norm_clip_critic: 50

#optimizer_epsilon: 0.01

learner: "facmac_td3_learner"
mac: "facmac_td3_mac"
critic_controller: "factorized_td3_controller"
agent: "rnn_actor"
critic: "double_critic"
mixer: "qmix"

use_state_as_input: False
critic_use_state_as_input: True
input_window: -1
start_training_actor_steps: 0

mixing_embed_dim: 64
hypernet_layers: 2
hypernet_embed: 64
hyper_initialization_nonzeros: 0
hidden_dim: 256

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 200

save_model: False
save_model_interval: 50000

save_model_end: True

#checkpoint_path: "D:/MAI/TFM/Resultats/many_swimmer/compare_facmac_td3_1/experiment_13/run_1/models" 
#evaluate: True