# --- FACMAC specific parameters ---

name: "facmac"

seed: 0

add_agent_id: False
critic_add_agent_id: False

buffer_transitions: True
num_envs: 1
n_batches_to_sample: -1
batch_size: 100
buffer_size: 50000
t_max: 100000

start_steps: 0
decay_type: linear
power: 1 # only applies to polynomial decay_type
sigma_start: 0.2
sigma_finish: 0.05
sigma_anneal_time: 100000

critic_use_previous_transitions: False
num_previous_transitions: 0

update_actor_with_joint_qs: True

gamma: 0.99

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.8
lr_decay_episodes: 10000

grad_norm_clip_actor: 0.5
grad_norm_clip_critic: 0.5

#optimizer_epsilon: 0.01

learner: "facmac_learner"
controller: "facmac_controller"
critic_controller: "factorized_critic_controller"
agent: "mlp_actor"
critic: "mlp"
mixer: "qmix"

mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 32
hyper_initialization_nonzeros: 0
hidden_dim: 64

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 2000

save_model: False
save_model_interval: 500000

actions_regularization: False

save_model_end: True

#checkpoint_path: D:/MAI/TFM/Resultats/many_swimmer/FACMAC/compare_20/experiment_89/run_2/models
#evaluate: True