# --- FACMAC distribution specific parameters ---

name: "facmac_distribution"

#seed: 1412

add_agent_id: True
add_last_action: True

runner: "parallel"
buffer_transitions: True
batch_size_run: 8
n_batches_to_sample: 512
batch_size: 128
buffer_size: 1000000
t_max: 1000000

entropy_coef: 0.1

gamma: 0.9999

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.9
lr_decay_episodes: 20

grad_norm_clip_actor: 50
grad_norm_clip_critic: 50

critic_use_previous_transitions: False
num_previous_transitions: 0

#optimizer_epsilon: 0.01

learner: "facmac_distribution_learner"
mac: "facmac_distribution_mac"
critic_controller: "factorized_no_rnn_controller"
agent: "mlp_mean_log_std"
critic: "mlp"
mixer: "vdn"

mixing_embed_dim: 64
hypernet_layers: 2
hypernet_embed: 64
hyper_initialization_nonzeros: 0
hidden_dim: 64

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 200

save_model: False
save_model_interval: 50000

save_model_end: True