# --- FACMAC specific parameters ---

name: "facmac"

seed: 1412

add_agent_id: False
add_last_action: True
critic_add_agent_id: False
critic_add_last_action: True

runner: "parallel"
buffer_transitions: False
batch_size_run: 8
n_batches_to_sample: 3
batch_size: 50
buffer_size: 4000
t_max: 1000000

start_steps: 0
sigma_start: 0.2
sigma_finish: 0.05
sigma_anneal_time: 1000000

gamma: 0.99

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.9
lr_decay_episodes: 20

grad_norm_clip_actor: 50
grad_norm_clip_critic: 50

#optimizer_epsilon: 0.01

learner: "facmac_learner"
mac: "facmac_mac"
critic_controller: "factorized_controller"
agent: "rnn_actor"
critic: "rnn"
mixer: "qmix"

mixing_embed_dim: 64
hypernet_layers: 2
hypernet_embed: 64
hyper_initialization_nonzeros: 0
hidden_dim: 64

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 200

save_model: False
save_model_interval: 50000

actions_regularization: False

save_model_end: True

#checkpoint_path: "D:/MAI/TFM/Resultats/swimmer/FACMAC/compare_13/experiment_53/run_1/models" 
#evaluate: True