# --- FACMAC specific parameters ---

name: "facmac"

seed: 0

add_agent_id: False
critic_add_agent_id: False

runner: "parallel"
buffer_transitions: True
batch_size_run: 8
n_batches_to_sample: 1000
batch_size: 100
buffer_size: 100000
t_max: 4000000

start_steps: 10000
sigma_start: 0.5
sigma_finish: 0.05
sigma_anneal_time: 4000000

critic_use_previous_transitions: False
num_previous_transitions: 0

update_actor_with_joint_qs: True

gamma: 0.99

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.8
lr_decay_episodes: 100000

grad_norm_clip_actor: 0.5
grad_norm_clip_critic: 0.5

#optimizer_epsilon: 0.01

learner: "facmac_no_rnn_learner"
mac: "facmac_no_rnn_mac"
critic_controller: "factorized_no_rnn_controller"
agent: "mlp_actor"
critic: "mlp"
mixer: "qmix"

mixing_embed_dim: 64
hypernet_layers: 2
hypernet_embed: 64
hyper_initialization_nonzeros: 0
hidden_dim: 64

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 2000

save_model: False
save_model_interval: 500000

actions_regularization: False

save_model_end: True

#checkpoint_path: C:/Users/quim1/Desktop/src/results/manyagent_swimmer/facmac/experiment_127/run_1/models
#evaluate: True