# --- FACMAC TD3 specific parameters ---

name: "facmac_td3"

seed: 0

add_agent_id: False
critic_add_agent_id: False

runner: "parallel"
buffer_transitions: True
batch_size_run: 8
n_batches_to_sample: 1000
batch_size: 100
buffer_size: 500000
t_max: 4000000

start_steps: 10000
decay_type: polynomial
power: 0.5 # only applies to polynomial decay_type
sigma_start: 0.5
sigma_finish: 0.05
sigma_anneal_time: 4000000

use_ornstein: True
ou_theta: 0.15
ou_sigma: 0.2
ou_noise_scale: 0.3

use_training_steps_to_compute_target_noise: True
target_sigma_start: 0.2
target_sigma_finish: 0.05
target_sigma_anneal_time: 500000

target_noise_clipping: 0.2
clip_exploration_actions: False
decay_clipped_noise: False
noise_clipping: 0.2
clip_noise_end: 0.05

gamma: 0.99

update_actor_targets_freq: 2

critic_use_previous_transitions: False
num_previous_transitions: 0

update_actor_with_joint_qs: False

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.9
lr_decay_episodes: 20

grad_norm_clip_actor: 0.5
grad_norm_clip_critic: 0.5

#optimizer_epsilon: 0.01

learner: "facmac_td3_no_rnn_learner"
mac: "facmac_td3_no_rnn_mac"
critic_controller: "factorized_td3_no_rnn_controller"
agent: "shared_but_first_actor_mlp"
critic: "shared_but_first_double_critic"
mixer: "qmix"

mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 32
hyper_initialization_nonzeros: 0
hidden_dim: 64

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 20000

actions_regularization: False

save_model: False
save_model_interval: 2000000

save_model_end: True

#checkpoint_path: D:/MAI/TFM/Resultats/many_swimmer/FACMAC_TD3/compare_10/experiment_187/run_2/models
#evaluate: True