# --- IQL specific parameters ---

name: "iql"

seed: 0

add_agent_id: False
add_last_action: True

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0

num_envs: 1
batch_size: 20
buffer_size: 1000
t_max: 100000

lr: 0.001
lr_decay: False
lr_decay_gamma: 0.9
lr_decay_episodes: 50

grad_norm_clip: 0.5

#optimizer_epsilon: 0.01

learner: "q_learner"
mac: "basic_mac"
agent: "rnn"
mixer: ~

double_q: True

hidden_dim: 64

target_update_mode: 'soft'
hard_update_interval: 200
target_update_tau: 0.005

save_model: False
save_model_interval: 5000

save_model_end: True

#checkpoint_path: "D:/MAI/TFM/TFM/results/pistonball_reward_2_actions/qmix/51/models" 
#evaluate: True
