# --- JAD3 specific parameters ---

name: "jad3"

seed: 0

add_agent_id: False
critic_add_agent_id: False

buffer_transitions: True
num_envs: 1
n_batches_to_sample: -1
batch_size: 256
buffer_size: 100000
t_max: 100000

increase_step_counter: False
use_training_steps_to_compute_target_noise: False

start_steps: 10000

decay_type: linear
power: 0.5 # only applies to polynomial decay_type

sigma_start: 0.2
sigma_finish: 0.1
sigma_anneal_time: 100000

target_sigma_start: 0.5
target_sigma_finish: 0.2
target_sigma_anneal_time: 100000
target_noise_clipping: 0.5

gamma: 0.99

update_actor_targets_freq: 2

critic_use_previous_transitions: False
num_previous_transitions: 0

update_actor_with_joint_qs: False
use_min_to_update_actor: True

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.9
lr_decay_episodes: 20

grad_norm_clip_actor: 0.5
grad_norm_clip_critic: 0.5

#optimizer_epsilon: 0.01

learner: "jad3_learner"
controller: "jad3_controller"
critic_controller: "jad3_critic_controller"
agent: "mlp_actor"
critic: "double_critic"
mixer: "qmix"

mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 32
hyper_initialization_nonzeros: 0
hidden_dim: 64

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 20000

actions_regularization: False

save_model: True
save_model_interval: 100000

save_model_end: True

#checkpoint_path: D:/MAI/TFM/Resultats/Ant-v4/experiment_58/run_2/models
#evaluate: True