# --- MADDPG Discrete action space specific parameters ---

name: "maddpg_discrete"

seed: 0

add_agent_id: False
add_last_action: True
critic_add_agent_id: False

num_envs: 1
batch_size: 20
buffer_size: 1000
t_max: 100000

use_epsilon_greedy: True
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0
epsilon_anneal_time: 100000
evaluation_epsilon: 0

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.9
lr_decay_episodes: 20

grad_norm_clip_actor: 50
grad_norm_clip_critic: 50

use_td_lambda: True
td_lambda: 0.8

gamma: 0.99

#optimizer_epsilon: 0.0001

learner: "maddpg_discrete_learner"
controller: "maddpg_discrete_controller"
critic_controller: "maddpg_discrete_critic_controller"
agent: "rnn"
critic: "centralized_mlp"

hidden_dim: 64
hidden_dim_critic: 256

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 200

save_model: False
save_model_interval: 50000

save_model_end: True

#checkpoint_path: "D:/MAI/TFM/Resultats/pistonball_discrete/MADDPG/compare_2/experiment_60/run_3/models" 
#evaluate: True