# --- MADDPG specific parameters ---

name: "maddpg"

seed: 0

add_agent_id: False
add_last_action: False
critic_add_agent_id: False

buffer_transitions: True
num_envs: 1
n_batches_to_sample: -1
batch_size: 100
buffer_size: 50000
t_max: 50000

start_steps: 10000
decay_type: linear
power: 1 # only applies to polynomial decay_type
sigma_start: 0.1
sigma_finish: 0.1
sigma_anneal_time: 100000

gamma: 0.99

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.9
lr_decay_episodes: 100

grad_norm_clip_actor: 500
grad_norm_clip_critic: 500

#optimizer_epsilon: 0.01

learner: "maddpg_learner"
mac: "facmac_mac"
critic_controller: "maddpg_controller"
agent: "mlp_actor"
critic: "centralized_mlp"

hidden_dim: 64
hidden_dim_critic: 256

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 200

save_model: False
save_model_interval: 500000

actions_regularization: False

save_model_end: True

checkpoint_path: D:/MAI/TFM/Resultats/many_swimmer/MADDPG/compare_3/experiment_94/run_2/models
evaluate: True