# --- QMIX specific parameters ---

name: "qmix"

seed: 0

add_agent_id: False
add_last_action: False

runner: "parallel"
batch_size_run: 1
batch_size: 32
buffer_size: 5000
t_max: 100000

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 30000
evaluation_epsilon: 0

lr: 0.0005
lr_decay: False
lr_decay_gamma: 0.9
lr_decay_episodes: 50

grad_norm_clip: 10

optimizer_epsilon: 0.00001

mac: "basic_mac"
agent: "rnn"
learner: "q_learner"
mixer: "qmix"

double_q: True

mixing_embed_dim: 64
hypernet_layers: 2
hypernet_embed: 64
hidden_dim: 32

target_update_mode: 'soft'
hard_update_interval: 200
target_update_tau: 0.005

save_model: False
save_model_interval: 5000

save_model_end: True

#checkpoint_path: "D:/MAI/TFM/TFM/results/pistonball_reward_2_actions/qmix/51/models" 
#evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
