# --- QMIX specific parameters ---

name: "qmix"

seed: 1412

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0

lr: 0.001
grad_norm_clip: 50

optimizer_epsilon: 0.01

obs_agent_id: True
obs_last_action: True
obs_individual_obs: False

mac: "basic_mac"
agent: "rnn"
agent_output_type: "q"
learner: "q_learner"
mixer: "qmix"

runner: "episode"
batch_size_run: 1
t_max: 100000

buffer_size: 1000
batch_size: 20

test_nepisode: 100
test_interval: 5000

target_update_mode: 'soft'
hard_update_interval: 200
target_update_tau: 0.005

save_model: False
save_model_interval: 5000

double_q: True
hidden_dim: 64
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

standardise_returns: False
standardise_rewards: False

l2_reg_coef: 0

lr_decay: False
lr_decay_gamma: 0.9
lr_decay_episodes: 50

#checkpoint_path: "D:/MAI/TFM/TFM/results/pistonball_reward_2_actions/qmix/51/models" 
#evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
#load_step: 997800