# --- QMIX specific parameters ---

name: "qmix"

seed: 0

add_agent_id: False
add_last_action: True

num_envs: 1
batch_size: 20
buffer_size: 1000
t_max: 50000

increase_step_counter: False

action_selector: "epsilon_greedy"
epsilon_start: 1
epsilon_finish: 0.05
epsilon_anneal_time: 10000
evaluation_epsilon: 0

lr: 0.001
lr_decay: False
lr_decay_gamma: 0.9
lr_decay_episodes: 50

grad_norm_clip: 0.5

#optimizer_epsilon: 0.0001

controller: "basic_controller"
agent: "rnn"
learner: "q_learner"
mixer: "qmix"

double_q: True

mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 32
hidden_dim: 64

target_update_mode: 'soft'
hard_update_interval: 200
target_update_tau: 0.005

save_model: True
save_model_interval: 10000

save_model_end: True

checkpoint_path: D:/MAI/TFM/Resultats/pistonball_discrete/QMIX/compare_1/qmix/experiment_12/run_3/models
evaluate: True
