# --- TD3 specific parameters ---

name: "td3"

seed: 0

runner: "parallel"
buffer_transitions: True
batch_size_run: 1
n_batches_to_sample: 1000
batch_size: 256
buffer_size: 1000000
t_max: 1000000

start_steps: 25000
decay_type: polynomial
power: 0.5 # only applies to polynomial decay_type
sigma_start: 0.5
sigma_finish: 0.05
sigma_anneal_time: 1000000

use_training_steps_to_compute_target_noise: True
target_sigma_start: 0.5
target_sigma_finish: 0.05
target_sigma_anneal_time: 1000000

target_noise_clipping: 0.2
decay_clipped_noise: False
clip_noise_end: 0.05

gamma: 0.9999

update_actor_targets_freq: 2

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.9
lr_decay_episodes: 20

grad_norm_clip_actor: 0.5
grad_norm_clip_critic: 0.5

#optimizer_epsilon: 0.01

learner: "td3_learner"
mac: "td3_mac"
critic_controller: "td3_controller"
agent: "mlp_actor"
critic: "double_critic"

hidden_dim: 256

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 200

save_model: False
save_model_interval: 200000

save_model_end: True

#checkpoint_path: "C:/Users/quim1/Desktop/src/results/Swimmer/td3/experiment_3/run_1/models" 
#evaluate: True
