# --- TD3 specific parameters ---

name: "td3"

seed: 0

runner: "parallel"
buffer_transitions: True
batch_size_run: 8
n_batches_to_sample: 1000
batch_size: 100
buffer_size: 1000000
t_max: 4000000

start_steps: 10000

sigma_start: 0.3
sigma_finish: 0.1
sigma_anneal_time: 1000000

target_sigma_start: 0.2
target_sigma_finish: 0.05
target_sigma_anneal_time: 1000000

gamma: 0.9999

update_actor_targets_freq: 1
target_noise_clipping: 0.5

lr: 0.001
critic_lr: 0.001
lr_decay_actor: False
lr_decay_critic: False
lr_decay_gamma: 0.9
lr_decay_episodes: 20

grad_norm_clip_actor: 50000
grad_norm_clip_critic: 50000

#optimizer_epsilon: 0.01

learner: "td3_learner"
mac: "td3_mac"
critic_controller: "td3_controller"
agent: "mlp_actor"
critic: "double_critic"

hidden_dim: 256

target_update_mode: "soft"
target_update_tau: 0.005
hard_update_interval: 200

save_model: False
save_model_interval: 50000

save_model_end: True

#load_step: 561000
#checkpoint_path: "D:/MAI/TFM/TFM/results/pistonball_reward_2_actions/facmac_pettingzoo/196/models" 
#evaluate: True # Evaluate model for test_nepisode episodes and quit (no training)
