# --- VDN specific parameters ---

name: "vdn"

seed: 0

add_agent_id: False
add_last_action: True

num_envs: 1
batch_size: 20
buffer_size: 1000
t_max: 50000

increase_step_counter: False

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 30000
evaluation_epsilon: 0

lr: 0.001
lr_decay: False
lr_decay_gamma: 0.9
lr_decay_episodes: 50

grad_norm_clip: 50

#optimizer_epsilon: 0.0001

mac: "basic_mac"
agent: "rnn"
learner: "q_learner"
mixer: "vdn"

double_q: True

mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 32
hidden_dim: 256

target_update_mode: 'soft'
hard_update_interval: 200
target_update_tau: 0.005

save_model: True
save_model_interval: 10000

save_model_end: True

#checkpoint_path: "D:/MAI/TFM/TFM/results/pistonball/qmix/experiment_75/run_1/models" 
#evaluate: True # Evaluate model for test_nepisode episodes and quit (no training)
