env: "mujoco_multi"

env_args:
    episode_limit: 1000
    scenario: "Humanoid-v4"
    agent_conf: "9|8"
    agent_obsk: 0
    obs_add_global_pos: False
    custom_args:
        #healthy_reward: 1
        render_mode: ~

t_max: 700000

repetitions: 1