env: "mujoco_multi"

env_args:
    episode_limit: 1000
    scenario: "Ant-v4"
    agent_conf: "2x4"
    agent_obsk: 0
    global_categories: "qvel"
    #healthy_reward: 0
    #ctrl_cost_weight: 0.01
    render_mode: human

save_frames: False

repetitions: 1

test_interval: 20000
test_nepisode: 10
log_interval: 5000
runner_log_interval: 5000
learner_log_interval: 5000