env: "mujoco_multi"

env_args:
    episode_limit: 1000
    scenario: "manyagent_swimmer"
    agent_conf: "10x2"
    agent_obsk: 0
    #global_categories: "qpos,qvel"
    #render_mode: human

repetitions: 1

test_interval: 20000
test_nepisode: 10
log_interval: 5000
runner_log_interval: 5000
learner_log_interval: 5000