env: "pettingzoo"

env_args:
  key: 'pistonball_reward_2_actions'
  pretrained_wrapper: null
  continuous: False
  num_pistons: 15
  render: False
  time_penalty: -0.25
  alpha: 0.2


test_greedy: True
test_nepisode: 100
stop_return: 150

test_interval: 5000
log_interval: 5000
runner_log_interval: 5000
learner_log_interval: 5000
t_max: 130000
repetitions: 5 
