env: "pettingzoo"

env_args:
    env_name: 'pistonball'
    num_pistons: 15
    continuous: False
    episode_limit: 125
    time_penalty: -0.25
    #render_mode: 'human'

repetitions: 1

test_interval: 1000
test_nepisode: 10
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
