env: "pettingzoo"

env_args:
    env_name: 'pistonball'
    num_pistons: 100
    continuous: False
    episode_limit: 125
    time_penalty: -0.25
    use_flag_version: True
    #render_mode: 'human'

repetitions: 1

#save_frames: True

test_interval: 1000
test_nepisode: 25
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
