env: "pettingzoo_continuous"

env_args:
    env_name: 'pistonball'
    num_pistons: 15
    continuous: True
    episode_limit: 125
    time_penalty: -0.25
    use_flag_version: False
    #render_mode: 'human'

repetitions: 1

log_interval: 1000
test_interval: 1000
test_nepisode: 10
runner_log_interval: 1000
learner_log_interval: 1000
