env: "pettingzoo_continuous"

env_args:
    env_name: 'pistonball'
    num_pistons: 15
    continuous: True # Do not change
    episode_limit: 125 # Do not change
    time_penalty: -0.25
    #render_mode: human

repetitions: 1

save_frames: True

test_interval: 1000
test_nepisode: 25
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
