env: "pettingzoo"

env_args:
    env_name: 'pistonball'
    num_pistons: 100
    continuous: False # Do not change
    episode_limit: 125 # Do not change
    time_penalty: -0.25 # At each step we subtract that amount from the reward
    render_mode: 'rgb_array'

repetitions: 1

save_frames: True

test_interval: 1000
test_nepisode: 25
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
