env: "pettingzoo_continuous"

env_args:
  key: 'pistonball_positions_global_2_actions'
  pretrained_wrapper: null
  continuous: True
  num_pistons: 15
  render: False
  time_penalty: -0.25
  alpha: 0.2


log_interval: 5000
test_interval: 5000
test_nepisode: 100
runner_log_interval: 5000
learner_log_interval: 5000
repetitions: 5
