env: "pettingzoo"

env_args:
  key: 'pistonball_positions_global_2_actions'
  pretrained_wrapper: null
  continuous: False
  num_pistons: 15
  render: False
  time_penalty: -0.25
  alpha: 0.2


test_interval: 1000
test_nepisode: 100
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
repetitions: 5
